version: '3.6'
services:
  web:
    image: nginx:1.22
    container_name: magento-nginx
    hostname: magento-nginx
    ports:
      - "80:80"
    volumes:
      - ~/proyectos/magento/source:/var/www/html
      - ./etc/infrastructure/nginx/1.22/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/infrastructure/var/run:/var/run
 #   depends_on:
 #     - php
    networks:
      - frontend

  php:
    container_name: magento-php
    hostname: magento-php
    build:
      context: ./dockerfiles/php/8.2
    volumes:
      - ./etc/infrastructure/php/8.2/php.ini:/usr/local/etc/php.d/load.ini
      - ./etc/infrastructure/php/8.2/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm-load.conf
      - ./etc/infrastructure/php/8.2/www.conf:/usr/local/etc/php-fpm.d/www-load.conf
      - ~/databases/storage/mariadb/magento:/var/lib/mysql
      - ~/.tmp/composer:/var/www/.composer
      - ~/proyectos/magento/source:/var/www/html
    depends_on:
      - redis
      - rabbitmq
      - db
      - elasticsearch
    networks:
      - frontend
      - backend

  db:
    container_name: magento-db
    hostname: magento-db
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - ~/databases/storage/mariadb/magento:/var/lib/mysql
    networks:
      - backend

  elasticsearch:
    hostname: magento-elasticsearch
    container_name: magento-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    networks:
      - backend

  rabbitmq:
    hostname: magento-rabbitmq
    container_name: magento-rabbitmq
    image: rabbitmq:3.11-management
    networks:
      - backend

  redis:
    hostname: magento-redis
    container_name: magento-redis
    image: redis:7.0
    networks:
      - backend

networks:
  frontend:
  backend: